Repository iqm-finland/cirq-on-iqm, pull requests merged in 2021-06, with the labels that each got.

#11 Add workflow for tox test
  .github/workflows/ci.yml
Labels: CI/CD, testing

#21 Remove superfluous gate classes, simplify gate decompositions
  examples/demo_adonis.py
  src/cirq_iqm/__init__.py
  src/cirq_iqm/adonis.py
  src/cirq_iqm/extended_qasm_parser.py
  src/cirq_iqm/iqm_client.py
  src/cirq_iqm/iqm_device.py
  src/cirq_iqm/iqm_gates.py
  src/cirq_iqm/iqm_operation_mapping.py
  src/cirq_iqm/iqm_remote.py
  src/cirq_iqm/valkmusa.py
  tests/adonis_test.py
  tests/iqm_client_test.py
  tests/iqm_gates_test.py
  tests/iqm_remote_test.py
  tests/optimization_test.py
  tests/test_iqm_gates.py
  tests/valkmusa_test.py
Labels: cleanup, enhancement

#22 Update the project setup. Generate API docs using sphinx.ext.autosummary.
  .github/workflows/ci.yml
  .pylintrc
  CHANGELOG.rst
  README.rst
  docs/API.rst
  docs/_templates/autosummary-class-template.rst
  docs/_templates/autosummary-module-template.rst
  docs/api/API.rst
  docs/api/adonis.rst
  docs/api/iqm_device.rst
  docs/api/iqm_gates.rst
  docs/api/valkmusa.rst
  docs/conf.py
  docs/index.rst
  docs/license.rst
  pyproject.toml
  setup.cfg
  setup.py
  src/cirq_iqm/iqm_device.py
  tox.ini
Labels: documentation, infrastructure
