Repository iqm-finland/cirq-on-iqm, pull requests merged in 2021-07, with the labels that each got.

#24 Update the docs for the public release.
  README.rst
  docs/index.rst
  examples/usage.ipynb
  setup.cfg
Labels: documentation

#29 Bugfix: off-by-one bug in IQMDevice.map_circuit
  CHANGELOG.rst
  src/cirq_iqm/adonis.py
  src/cirq_iqm/iqm_device.py
  src/cirq_iqm/valkmusa.py
  tests/test_qubit_mapping.py
Labels: bug

#33 Publish documentation on GitHub Pages with an Action
  .github/workflows/release.yml
  setup.cfg
Labels: CI/CD, documentation
